### ISSUE TITLE
AQD - Upgradeable Gyroscopes

### ISSUE THREAD

**Issue by enenra** [enenra/aqdse#55]
Implemented as 3 new blocks.

* **Gyro Booster** is a 2x1x1 block available for small and large grid and has 4 mountpoints for normal gyros. It boosts their output significantly.

* **Large Gyro** is a 3x3x3 block only available for large grid. It is stronger than the 27 gyros it would replace and has 4 upgrade module slots.

* **Gyro Upgrade Module** is a 3x3x1 block only available for large grid. It slots around the large gyro and boosts its output significantly.

**ToDo**

SBC:
- [x] Balance Gyro Booster
- [x] Balance Large Gyro
- [x] Balance Gyro Upgrade Module

Models:
- [x] Full set of models for Gyro Booster (LG)
- [x] Full set of models for Gyro Booster (SG)
- [x] Full set of models for Large Gyro
- [x] Full set of models for Gyro Upgrade Module
- [x] Adjust Vanilla Small and Large Gyro model

**Comment by enenra** [comment]
A first prototype has been created and is working.
